Main page
elemntorBootkamp/frontend pull request #28
Opened 2023-06-07 07:45 UTC by shifraDomb

2023-06-12 10:18 UTC, elemntorBootkamp requested changes

2023-06-12 10:18 UTC, elemntorBootkamp commented on cypress/e2e/todo.cy.js
this file is deleted? or empty file?

2023-06-12 10:29 UTC, shifraDomb commented on cypress/videos/todo.cy.js.mp4
this file delated

2023-06-12 10:29 UTC, shifraDomb commented on cypress/e2e/todo.cy.js
deleted

2023-06-12 10:46 UTC, shifraDomb commented on cypress/e2e/signup.cy.js
זה קומפוננטה חסרת טעם כרגע אין עוד בדיקות להוסיף לה

2023-06-12 10:46 UTC, shifraDomb commented on cypress/e2e/example.cy.js
מחקתי...

2023-06-15 10:55 UTC, MichalRevivo approved these changes

2023-06-15 10:56 UTC, MichalRevivo commented
wow!

2023-06-15 10:58 UTC, shifraDomb commented on cypress/screenshots/todo.cy.js/Header -- should log in successfully (failed).png
delete

2023-06-15 11:05 UTC, MichalRevivo approved these changes

2023-07-12 12:49 UTC, closed without merging